export const KAWAIIVERSE_NFT1155_ADDRESS = process.env.REACT_APP_KAWAIIVERSE_NFT1155_ADDRESS;
export const KAWAIIVERSE_STORE_ADDRESS = process.env.REACT_APP_KAWAII_STORE_ADDRESS;
export const KAWAII_TOKEN_ADDRESS = process.env.REACT_APP_KAWAII_TOKEN_ADDRESS;
export const FACTORY_ADDRESS = process.env.REACT_APP_FACTORY_ADDRESS;
